version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es
    environment:
      - node.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS= -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/var/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.0.0
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    # Elasticsearch Start Dependency
    depends_on:
      - es
    networks:
      - elastic

volumes:
  data01:
    driver: local
  kibana:
    driver: local

networks:
  elastic:
    driver: bridge